# service yaml specification
apiVersion: v1
kind: Service
metadata:
  name: iris-predictor-service
spec:
  selector:
    app: iris-fastapi-service
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer